name: AlternaMatch - Scraper Alternances & Stages

on:
  schedule:
    - cron: '0 */2 * * *'
  workflow_dispatch:

jobs:
  scraper:
    runs-on: ubuntu-latest
    steps:
      - name: Récupérer le code
        uses: actions/checkout@v4

      - name: Installer Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Installer les dépendances
        run: pip install requests beautifulsoup4

      - name: Lancer le scraper
        env:
          EMAIL_DESTINATAIRE: ${{ secrets.EMAIL_DESTINATAIRE }}
          EMAIL_EXPEDITEUR: ${{ secrets.EMAIL_EXPEDITEUR }}
          EMAIL_MOT_DE_PASSE: ${{ secrets.EMAIL_MOT_DE_PASSE }}
        run: python scraper.py
